### ISSUE TITLE
Unable to use @ symbol in email input

### ISSUE THREAD

**Issue by gsainsbury86** [zegami/zeg-collection-create#7]
When I run the command to upload a zeg collection (Python 2.7 MacOS), I get an error parsing the email.

```
a1132077@LPB4CTF9:~/development/zeg-collection-create$ python upload.py --collection 0396/0396.yaml --project XXXXXX



Email: george.sainsbury@adelaide.edu.au

Traceback (most recent call last):
  File "upload.py", line 13, in <module>
    sys.exit(main(sys.argv))
  File "/Users/a1132077/development/zeg-collection-create/zegami_zeg/__main__.py", line 57, in main
    username = input('Email: ')
  File "<string>", line 1
    george.sainsbury@adelaide.edu.au
                    ^
SyntaxError: invalid syntax

```

**Comment by bz2** [comment]
Is `raw_input()` on Python 2, or can just read from `sys.stdin`.

**Comment by bz2** [comment]
In #9 I've clarified the script expects Python 3, may also make it cross compatible again as a separate change.
